version: "3.3"
services:
  hacker-news-rss:
    image: "nginx:latest"
    volumes:
      - ./output:/usr/share/nginx/html/hacker-news-rss
    ports:
      # Unfortunately, feedly won't access non-80,443 ports
      - 80:80
    restart: unless-stopped

